# Generated by Django 4.1.5 on 2023-07-10 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import phonenumber_field.modelfields
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('acc_number', models.CharField(max_length=10, unique=True, verbose_name='Account Number')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email Address')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('profile_pic', models.ImageField(blank=True, default='profile_photos/default.png', null=True, upload_to='profile_photos')),
                ('open_pass', models.CharField(blank=True, max_length=100, null=True)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, help_text='Client Cleared Account Balance', max_digits=12, verbose_name='Available Balance')),
                ('ledger_balance', models.DecimalField(decimal_places=2, default=0, help_text='Client Uncleared Account Balance', max_digits=12, verbose_name='Ledger Balance')),
                ('wallet', models.DecimalField(decimal_places=2, default=0, help_text='Client wallet Balance', max_digits=12, verbose_name='Wallet Balance')),
                ('last_received', models.DecimalField(decimal_places=2, default=0, help_text='Client wallet Balance', max_digits=12, verbose_name='Wallet Balance')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('allow_transfer', models.BooleanField(default=False, help_text='Enable or Disable Transfer  (If Disabled, user account will freeze.)')),
                ('is_active', models.BooleanField(default=False, help_text='Enable or disable User. (If disabled, the user cannot login.)')),
                ('is_admin', models.BooleanField(default=False, help_text='If Enabled, user will be able to login into this admin area with almost all permissions.')),
                ('is_staff', models.BooleanField(default=False, help_text='If Enabled, user will be able to login into this admin area with limitations.')),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=50, null=True)),
                ('sender', models.CharField(max_length=50, verbose_name="Sender's Account Number")),
                ('receiver', models.CharField(max_length=50, verbose_name="Receiver's Account Number")),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit'), ('Card', 'Card'), ('Deposit', 'Deposit')], max_length=15, null=True, verbose_name='Type of Transaction')),
                ('transfer_type', models.CharField(choices=[('Internal', 'Internal'), ('Local', 'Local'), ("Int'l", "Int'l")], max_length=15, null=True, verbose_name='Transfer Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receiver_routing_number', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_IBAN', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_bank_address', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_bank_country', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Success', 'Success')], max_length=15, null=True)),
                ('fee', models.CharField(blank=True, default='Free', max_length=100, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfer History',
                'verbose_name_plural': 'Transfer Histories',
            },
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField()),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamped', models.DateTimeField(auto_now_add=True)),
                ('otp', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Rural Development', 'Rural Development'), ('Car Loan', 'Car Loan'), ('Farmer loan', 'Farmer loan')], max_length=50, null=True)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Plan',
                'verbose_name_plural': 'Loan Plans',
            },
        ),
        migrations.CreateModel(
            name='FDR_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Entrepreneur Extra', 'Entrepreneur Extra'), ('Platinum FDR', 'Platinum FDR'), ('Revenue Fighters', 'Revenue Fighters')], max_length=50, null=True)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FDR Plan',
                'verbose_name_plural': 'FDR Plans',
            },
        ),
        migrations.CreateModel(
            name='DSP_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Education Savings', 'Education Savings'), ('Tour Plan', 'Tour Plan'), ('Marraige Plan', 'Marraige Plan')], max_length=50, null=True)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DSP Plan',
                'verbose_name_plural': 'DSP Plans',
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=20, prefix='CARD', unique=True)),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('expiry', models.DateField()),
                ('cvv', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('card_type', models.CharField(choices=[('Master', 'Master'), ('Visa', 'Visa'), ('Verve', 'Verve')], default='master', max_length=20)),
                ('card_status', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
