# Generated by Django 4.1.5 on 2023-07-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_creditcard_amount_alter_creditcard_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
