# Generated by Django 4.1.5 on 2024-05-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_account_limit_otheraccounts_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='image',
            field=models.ImageField(blank=True, default='profile_photos/default.png', null=True, upload_to='beneficiary_photos'),
        ),
    ]
