# Generated by Django 4.1.5 on 2024-05-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_beneficiary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'usd'), ('gbp', 'gbp'), ('eur', 'eur')], default='Dollar', max_length=15, null=True),
        ),
    ]
