# Generated by Django 4.1.5 on 2024-05-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_beneficiary_country_alter_beneficiary_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='type',
            field=models.CharField(blank=True, choices=[('OWN BANK', 'OWN BANK'), ('LOCAL BANK', 'LOCAL'), ('INTL BANK', 'INTL BANK')], default='OWN BANK', max_length=15, null=True),
        ),
    ]
