# Generated by Django 4.1.5 on 2024-06-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_account_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferhistory',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Receiver's Account Name"),
        ),
    ]
