# Generated by Django 4.1.5 on 2024-07-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_transferhistory_receiver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='type',
            field=models.CharField(blank=True, choices=[('Internal', 'Internal'), ('Local', 'Local'), ("Int'l", "Int'l")], default='OWN BANK', max_length=15, null=True),
        ),
    ]
